package _09_OBJECT_ORIENTED_PROGRAMMING;

public class CLASS {

    /*
    EVERY OBJECT HAVE THE PROPERTY AND THE BEHAVIOUR
    THE PROPERTY CAN BE UNDERSTAND WITH THE HELP OF THE EXAMPLE
    SUCH AS THE TELEVISION HAS THE PROPERTY AS THE HEIGHT COLOR CURRENT CHANNEL
    AND THE BEHAVIOUR AS THE CHANGING THE CHANNEL AND THE CHANGING THE VOLUME OF THE TV
    THE BEHAVIOUR IS ALWAYS AFFECTED BY THE PROPERTY
    THE OBJECT CAN BE THINKED AS THE TV
    AND THE DESIGN OF THE TV IS THE CLASS
    ONE CLASS CAN HAVE MORE THE ONE OBJECT

     */
}
